### ISSUE TITLE
Doesn't compile in kernel 4.13

### ISSUE THREAD

**Issue by tigerofasia** [paralin/rtl8821au#7]
First of all thanks for making this. I'm just having a problem compiling this in my Linux Mint using kernel 4.13

Does this support that kernel or not yet?

Anyway, here are the messages with the error.

Cheers

```
root@tigerofasiaPC /home/tigerofasia/Desktop/rtl8821au-master # make
make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/4.13.0-45-generic/build M=/home/tigerofasia/Desktop/rtl8821au-master  modules
make[1]: Entering directory '/usr/src/linux-headers-4.13.0-45-generic'
  CC [M]  /home/tigerofasia/Desktop/rtl8821au-master/core/rtw_cmd.o
In file included from /home/tigerofasia/Desktop/rtl8821au-master/include/drv_types.h:32:0,
                 from /home/tigerofasia/Desktop/rtl8821au-master/core/rtw_cmd.c:22:
/home/tigerofasia/Desktop/rtl8821au-master/include/osdep_service.h: In function ‘thread_enter’:
/home/tigerofasia/Desktop/rtl8821au-master/include/osdep_service.h:343:2: error: implicit declaration of function ‘allow_signal’ [-Werror=implicit-function-declaration]
  allow_signal(SIGTERM);
  ^
/home/tigerofasia/Desktop/rtl8821au-master/include/osdep_service.h: In function ‘flush_signals_thread’:
/home/tigerofasia/Desktop/rtl8821au-master/include/osdep_service.h:353:6: error: implicit declaration of function ‘signal_pending’ [-Werror=implicit-function-declaration]
  if (signal_pending (current)) 
      ^
/home/tigerofasia/Desktop/rtl8821au-master/include/osdep_service.h:355:3: error: implicit declaration of function ‘flush_signals’ [-Werror=implicit-function-declaration]
   flush_signals(current);
   ^
In file included from /home/tigerofasia/Desktop/rtl8821au-master/include/drv_types.h:65:0,
                 from /home/tigerofasia/Desktop/rtl8821au-master/core/rtw_cmd.c:22:
/home/tigerofasia/Desktop/rtl8821au-master/core/rtw_cmd.c: In function ‘btinfo_evt_dump’:
/home/tigerofasia/Desktop/rtl8821au-master/include/rtw_debug.h:187:19: error: void value not ignored as it ought to be
  #define _seqdump seq_printf
                   ^
/home/tigerofasia/Desktop/rtl8821au-master/include/rtw_debug.h:242:7: note: in expansion of macro ‘_seqdump’
    if(_seqdump(sel, fmt, ##arg)) /*rtw_warn_on(1)*/; \
       ^
/home/tigerofasia/Desktop/rtl8821au-master/core/rtw_cmd.c:3293:2: note: in expansion of macro ‘DBG_871X_SEL_NL’
  DBG_871X_SEL_NL(sel, "cid:0x%02x, len:%u\n", info->cid, info->len);
  ^
/home/tigerofasia/Desktop/rtl8821au-master/include/rtw_debug.h:187:19: error: void value not ignored as it ought to be
  #define _seqdump seq_printf
                   ^
/home/tigerofasia/Desktop/rtl8821au-master/include/rtw_debug.h:242:7: note: in expansion of macro ‘_seqdump’
    if(_seqdump(sel, fmt, ##arg)) /*rtw_warn_on(1)*/; \
       ^
/home/tigerofasia/Desktop/rtl8821au-master/core/rtw_cmd.c:3296:3: note: in expansion of macro ‘DBG_871X_SEL_NL’
   DBG_871X_SEL_NL(sel, "byte2:%s%s%s%s%s%s%s%s\n"
   ^
/home/tigerofasia/Desktop/rtl8821au-master/include/rtw_debug.h:187:19: error: void value not ignored as it ought to be
  #define _seqdump seq_printf
                   ^
/home/tigerofasia/Desktop/rtl8821au-master/include/rtw_debug.h:242:7: note: in expansion of macro ‘_seqdump’
    if(_seqdump(sel, fmt, ##arg)) /*rtw_warn_on(1)*/; \
       ^
/home/tigerofasia/Desktop/rtl8821au-master/core/rtw_cmd.c:3308:3: note: in expansion of macro ‘DBG_871X_SEL_NL’
   DBG_871X_SEL_NL(sel, "retry_cnt:%u\n", info->retry_cnt);
   ^
/home/tigerofasia/Desktop/rtl8821au-master/include/rtw_debug.h:187:19: error: void value not ignored as it ought to be
  #define _seqdump seq_printf
                   ^
/home/tigerofasia/Desktop/rtl8821au-master/include/rtw_debug.h:242:7: note: in expansion of macro ‘_seqdump’
    if(_seqdump(sel, fmt, ##arg)) /*rtw_warn_on(1)*/; \
       ^
/home/tigerofasia/Desktop/rtl8821au-master/core/rtw_cmd.c:3311:3: note: in expansion of macro ‘DBG_871X_SEL_NL’
   DBG_871X_SEL_NL(sel, "rssi:%u\n", info->rssi);
   ^
/home/tigerofasia/Desktop/rtl8821au-master/include/rtw_debug.h:187:19: error: void value not ignored as it ought to be
  #define _seqdump seq_printf
                   ^
/home/tigerofasia/Desktop/rtl8821au-master/include/rtw_debug.h:242:7: note: in expansion of macro ‘_seqdump’
    if(_seqdump(sel, fmt, ##arg)) /*rtw_warn_on(1)*/; \
       ^
/home/tigerofasia/Desktop/rtl8821au-master/core/rtw_cmd.c:3314:3: note: in expansion of macro ‘DBG_871X_SEL_NL’
   DBG_871X_SEL_NL(sel, "byte5:%s%s\n"
   ^
cc1: some warnings being treated as errors
scripts/Makefile.build:316: recipe for target '/home/tigerofasia/Desktop/rtl8821au-master/core/rtw_cmd.o' failed
make[2]: *** [/home/tigerofasia/Desktop/rtl8821au-master/core/rtw_cmd.o] Error 1
Makefile:1550: recipe for target '_module_/home/tigerofasia/Desktop/rtl8821au-master' failed
make[1]: *** [_module_/home/tigerofasia/Desktop/rtl8821au-master] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.13.0-45-generic'
Makefile:1545: recipe for target 'modules' failed
make: *** [modules] Error 2

```

**Comment by tigerofasia** [comment]
Closing this issue. I fixed the issue on my end by installing this instead.

```
git clone https://github.com/abperiasamy/rtl8812AU_8821AU_linux.git
cd rtl8812AU_8821AU_linux
sudo make -f Makefile.dkms install
```
